### ISSUE TITLE
Link to HOT Export Tool

### ISSUE THREAD

**Issue by geohacker** [hotosm/osma-health#75]
Add a link to HOT Export Tool for each AOI. These can be predefined jobs in the countries.json file.

cc @smit1678 @awright @ascalamogna @kamicut

**Comment by kamicut** [comment]
@geohacker the HOT export tool asks for a list of features to be exported. What do you think we should export that would most be valuable for further analysis?

**Comment by smit1678** [comment]
I would probably say the POSM bundle format which includes all features and tags. 

Example export for Chobe: https://export.hotosm.org/en/v3/exports/f357a551-96f3-476b-a0dc-6813c6a5ce56

**Comment by kamicut** [comment]
@smit1678 In the example you linked, the yaml seems to have only buildings? 

```
buildings:
    types:
        - lines
        - polygons
    select:
        - name
        - building
    where: building IS NOT NULL
```

Should I clone the export with this config and change the AOIs?
